version: "3.9"
services:
  llama:
    container_name: llama_server
    image: llama-cpp-docker
    restart: unless-stopped
    environment:
      - GGML_CUDA_NO_PINNED=1
      - LLAMA_CTX_SIZE=2048
      - LLAMA_MODEL=/models/Meta-Llama-3.1-8B-Instruct-Q5_K_M.gguf
      - LLAMA_N_GPU_LAYERS=99
    volumes:
      - ./models:/models
    ports:
      - target: 8080
        published: 18080
        mode: host
